# Generated by Django 5.2 on 2025-07-04 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='desc',
            new_name='description',
        ),
    ]
